/**
 * Turn an embed-mode build (`PUBLIC_DELIVERY_EMBED=1`) into something a partner's page can include.
 *
 * WHY THIS EXISTS. A delivery is not a site we host: the partner serves ONE server-rendered page per
 * brand that loads every game built on our client technology, and that page is already inside
 * iframes they do not control — so there is no `index.html` of ours in the picture. They give us a
 * container div and a script tag whose URL they compose server-side:
 *
 *     <div id="game"></div>
 *     <script src="<?=baseUrl?><?=gameAlias?>/game.js"></script>
 *
 * The URL is the same shape for every game, so the filename must be FIXED — a content hash is not
 * merely unnecessary, the server could not know it. Their cache-buster is `versionPath`, a segment
 * of `baseUrl`: the whole folder moves per release.
 *
 * WHAT IT DOES. `bundleStrategy: 'single'` already emits the one thing we need — `start(element)`
 * out of `_app/immutable/bundle.<hash>.js` — but the knowledge of how to boot it (which global to
 * set, which stylesheets to attach, which hashed filename) lives in the `index.html` shell, which a
 * delivery never serves. So: read that shell, and write the same boot as a standalone `game.js`.
 *
 * It is generated rather than hand-written because every one of those three things is hash- or
 * build-stamped. A hand-written loader would be correct exactly until the next build.
 *
 * WHY A CLASSIC SCRIPT, NOT A MODULE. Their template writes a bare `<script src>`, and this way it
 * stays literally that — no `type="module"` to remember, on a page we do not own and cannot fix
 * after handover. `document.currentScript.src` gives us the same script-relative base
 * `import.meta.url` would, and the bundle itself is still imported as the module it is.
 *
 * ASSETS NEED NOTHING. The game builds its asset URLs from `import.meta.url`, so the module resolves
 * `assets/` against its own location on the CDN. That is what makes the `versionPath` folder move
 * work, and it is exactly what the default inline build breaks — an inline script has no `src` and
 * falls back to `document.baseURI`, i.e. the partner's page.
 *
 * See `docs/design/delivery-builds.md`.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const buildDir = resolve(process.cwd(), process.argv[2] ?? 'build');
const shellPath = resolve(buildDir, 'index.html');

let shell;
try {
	shell = readFileSync(shellPath, 'utf8');
} catch {
	throw new Error(`No ${shellPath} — run \`PUBLIC_DELIVERY_EMBED=1 vite build\` first.`);
}

/**
 * The shell's boot block, which is what we are re-expressing:
 *
 *     __sveltekit_1eyfpjo = { base: new URL(".", location).pathname.slice(0, -1) };
 *     const element = document.currentScript.parentElement;
 *     import("./_app/immutable/bundle.CiDIUBV1.js").then((app) => { app.start(element) });
 */
const kitGlobal = shell.match(/(__sveltekit_[a-z0-9]+)\s*=/)?.[1];
const bundle = shell.match(/import\("([^"]+bundle[^"]*\.js)"\)/)?.[1];

if (!kitGlobal || !bundle) {
	throw new Error(
		`${shellPath} does not look like a 'single' bundle build ` +
			`(kit global: ${kitGlobal ?? 'not found'}, bundle: ${bundle ?? 'not found'}). ` +
			`Was PUBLIC_DELIVERY_EMBED=1 set? The default build inlines the bundle instead.`,
	);
}

// Every stylesheet the shell attaches, in order: the build's own (relative, hashed) and any the
// app template hard-codes (Typekit). Harvested rather than listed, so adding a font provider to
// `app.html` reaches a delivery without anyone remembering this file.
const styles = [...shell.matchAll(/<link[^>]+rel="stylesheet"[^>]*>/g)]
	.map((m) => m[0].match(/href="([^"]+)"/)?.[1])
	.filter((href) => typeof href === 'string');

/**
 * The container. Fixed id for the same reason the filename is fixed: one page serves every game and
 * composes everything server-side, so there is nothing per-game to configure. `document.body` is
 * the fallback for opening the folder directly, which is how you check a delivery before shipping it.
 */
const loader = `/* Invisible Engine — embed loader. GENERATED by scripts/build-embed.mjs; do not edit.
 *
 * Usage, on a page that has already set window.params:
 *
 *     <div id="game"></div>
 *     <script src="{cdn}/{brand}/games/{versionPath}/{gameAlias}/game.js"></script>
 */
(function () {
	var script = document.currentScript;
	var here = (script && script.src) || document.baseURI;
	var url = function (path) {
		return new URL(path, here).href;
	};

	${JSON.stringify(styles)}.forEach(function (href) {
		var link = document.createElement('link');
		link.rel = 'stylesheet';
		link.href = url(href);
		document.head.appendChild(link);
	});

	// SvelteKit's routing base — about the DOCUMENT's url, not ours. The router has to resolve the
	// operator's page down to our single route or it renders its own 404 instead of the game, so
	// this is the same expression the generated shell uses: the page's own directory. (None of our
	// assets come through here; they follow the module's url to wherever the bundle was served.)
	window['${kitGlobal}'] = { base: new URL('.', location).pathname.replace(/\\/$/, '') };

	import(url(${JSON.stringify(bundle)})).then(function (app) {
		app.start(document.getElementById('game') || document.body);
	});
})();
`;

const out = resolve(buildDir, 'game.js');
writeFileSync(out, loader, 'utf8');
console.info(
	`[build-embed] wrote ${out}\n` +
		`             bundle: ${bundle}\n` +
		`             styles: ${styles.join(', ') || '(none)'}`,
);
