export type EmitterEventHotKey = {
	type: 'hotKey';
	key: string;
	action: 'keyUp' | 'keyDown';
	/** A `keyDown` the OS generated by auto-repeating a key that is held, not a new press. */
	repeat?: boolean;
};
